import type { Request, Response, NextFunction } from "express";
import { AppError } from "../lib/errors.js";
import { captureException } from "../lib/sentry.js";

// ─────────────────────────────────────────────────────────
// CENTRAL ERROR HANDLER
//
// Must be registered LAST with  app.use(errorHandler)
// Express recognises the 4-arg signature as an error handler.
//
// Logs structured JSON for every error with the requestId
// generated by the request-logger middleware.
// ─────────────────────────────────────────────────────────

function logError(
  level: "warn" | "error",
  type: string,
  requestId: string | undefined,
  details: Record<string, unknown>,
): void {
  console.error(
    JSON.stringify({
      level,
      type,
      requestId: requestId ?? null,
      ts: new Date().toISOString(),
      ...details,
    }),
  );
}

export function errorHandler(
  err: unknown,
  _req: Request,
  res: Response,
  _next: NextFunction,
): void {
  const requestId = res.locals.requestId as string | undefined;

  // ── Known application errors ───────────────────────────
  if (err instanceof AppError) {
    logError("warn", "AppError", requestId, {
      code: err.code,
      statusCode: err.statusCode,
      message: err.message,
    });

    res.status(err.statusCode).json({
      error: {
        code: err.code,
        message: err.message,
      },
    });
    return;
  }

  // ── Zod validation errors ──────────────────────────────
  if (
    err &&
    typeof err === "object" &&
    "issues" in err &&
    Array.isArray((err as any).issues)
  ) {
    logError("warn", "ZodError", requestId, {
      issueCount: (err as any).issues.length,
      issues: (err as any).issues,
    });

    res.status(400).json({
      error: {
        code: "ERR_VALIDATION",
        message: "Validation failed",
        details: (err as any).issues,
      },
    });
    return;
  }

  // ── Unexpected errors ──────────────────────────────────
  logError("error", "UnhandledError", requestId, {
    message: err instanceof Error ? err.message : String(err),
    stack: err instanceof Error ? err.stack : undefined,
  });

  // Report to Sentry (no-op unless configured).
  captureException(err, { requestId });

  const message =
    process.env.NODE_ENV === "production"
      ? "Internal server error"
      : err instanceof Error
        ? err.message
        : String(err);

  res.status(500).json({
    error: {
      code: "ERR_INTERNAL",
      message,
    },
  });
}
