-- Add display fields to shops table for Customer app rendering
ALTER TABLE shops ADD COLUMN IF NOT EXISTS rating DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE shops ADD COLUMN IF NOT EXISTS total_ratings INTEGER NOT NULL DEFAULT 0;
ALTER TABLE shops ADD COLUMN IF NOT EXISTS open_time VARCHAR(10) NOT NULL DEFAULT '08:00';
ALTER TABLE shops ADD COLUMN IF NOT EXISTS close_time VARCHAR(10) NOT NULL DEFAULT '20:00';
ALTER TABLE shops ADD COLUMN IF NOT EXISTS delivery_fee INTEGER NOT NULL DEFAULT 0;
ALTER TABLE shops ADD COLUMN IF NOT EXISTS min_order INTEGER NOT NULL DEFAULT 0;
